import type { Tool, Category } from './types'

export const categories: Category[] = [
  { id: 'all', name: 'All Tools', icon: '🧰', color: 'gray' },
  { id: 'json', name: 'JSON', icon: '📋', color: 'yellow' },
  { id: 'encoding', name: 'Encoding', icon: '🔐', color: 'blue' },
  { id: 'crypto', name: 'Crypto & Hash', icon: '🔒', color: 'red' },
  { id: 'string', name: 'String', icon: '🔤', color: 'green' },
  { id: 'number', name: 'Number', icon: '🔢', color: 'purple' },
  { id: 'datetime', name: 'Date & Time', icon: '📅', color: 'orange' },
  { id: 'web', name: 'Web', icon: '🌐', color: 'cyan' },
  { id: 'color', name: 'Color', icon: '🎨', color: 'pink' },
  { id: 'generator', name: 'Generators', icon: '⚡', color: 'indigo' },
  { id: 'formatter', name: 'Formatters', icon: '✨', color: 'teal' },
  { id: 'misc', name: 'Misc', icon: '🔧', color: 'slate' },
  { id: 'converter', name: 'Converter', icon: '🔄', color: 'violet' },
  { id: 'dotnet', name: '.NET / C#', icon: '💜', color: 'purple' },
  { id: 'ai', name: 'AI Tools', icon: '🤖', color: 'violet' },
]

export const tools: Tool[] = [
  // JSON
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, validate and beautify JSON data online',
    category: 'json',
    icon: '📋',
    tags: ['json', 'format', 'validate', 'beautify', 'online'],
    popular: true,
    supportsShare: true,
    suggestedTools: ['json-minifier', 'json-to-csv', 'json-diff'],
    seoTitle: 'JSON Formatter & Validator | DevTools Online',
    seoDescription: 'Free online JSON formatter, validator & beautifier. Paste JSON to auto-format, detect errors, collapse nodes — no signup, 100% client-side, works instantly.',
    howToUse: '1. **Paste** your JSON code into the input editor. \n2. The tool will **auto-format** and validate it immediately.\n3. Use the **Copy** button to get the beautified result.',
    commonErrors: '- **Syntax Errors**: Missing commas, trailing commas, or unquoted keys.\n- **Invalid Characters**: Hidden characters or smart quotes from word processors.',
  },
  {
    id: 'json-minifier',
    name: 'JSON Minifier',
    description: 'Minify and compress JSON data online',
    category: 'json',
    icon: '📉',
    tags: ['json', 'minify', 'compress', 'online'],
    supportsShare: true,
    suggestedTools: ['json-formatter', 'json-to-csv'],
    seoTitle: 'JSON Minifier & Compressor | DevTools Online',
    seoDescription: 'Minify and compress JSON data online — remove whitespace, reduce file size instantly. Free, no signup, 100% client-side, works in any browser.',
    howToUse: '1. **Input** your valid JSON data.\n2. The tool will **strip all whitespace** and comments if present.\n3. **Copy** the compact version for use in config or code.',
    commonErrors: '- **Malformed JSON**: Minification requires valid JSON input first.',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV',
    description: 'Convert JSON array data to CSV format online',
    category: 'json',
    icon: '📊',
    tags: ['json', 'csv', 'convert', 'online'],
    seoTitle: 'JSON to CSV Converter | DevTools Online',
    seoDescription: 'Convert JSON arrays to CSV format online instantly. Our free tool handles nested objects, flattens data for Excel, and allows downloading .csv files with no signup required.',
    howToUse: '1. **Paste** your JSON array or object into the input area.\n2. The tool will **auto-detect** the keys and flatten the structure.\n3. **Review** the table preview to ensure the columns are correct.\n4. **Download** the result as a `.csv` file or copy to your clipboard.',
    commonErrors: '- **Invalid JSON**: Ensure your input is a valid JSON array or object.\n- **Non-Array Input**: The tool works best with arrays of objects to create tabular rows.',
  },
  {
    id: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare and find differences between two JSON objects online',
    category: 'json',
    icon: '🔍',
    tags: ['json', 'diff', 'compare', 'online'],
    new: true,
    seoTitle: 'JSON Diff Tool — Compare JSON Objects | DevTools Online',
    seoDescription: 'Compare two JSON objects online and highlight differences in keys and values. Free JSON diff tool with side-by-side comparison, auto-sorting, and deep nested detection.',
    howToUse: '1. **Paste** your original JSON into the left panel.\n2. **Paste** the modified JSON into the right panel.\n3. The tool will **instantly highlight** differences (additions in green, deletions in red).\n4. Toggle **Auto-sort keys** if you want to ignore differences in property order.',
    commonErrors: '- **Syntax Errors**: Ensure both inputs are valid JSON before comparing.\n- **Large Payloads**: For extremely large files, the initial comparison may take a few seconds.',
  },

  // Encoding
  {
    id: 'base64-encode-decode',
    name: 'Base64 Encode/Decode',
    description: 'Encode and decode Base64 strings online',
    category: 'encoding',
    icon: '🔐',
    tags: ['base64', 'encode', 'decode', 'online'],
    popular: true,
    supportsShare: true,
    suggestedTools: ['json-formatter', 'jwt-decoder', 'url-encode-decode'],
    seoTitle: 'Base64 Encode & Decode | DevTools Online',
    seoDescription: 'Encode text or files to Base64 and decode Base64 strings online — free, instant, no upload to server. Drag & drop files, copy output in one click.',
    howToUse: '1. Enter the **text** or **drag and drop a file** into the input area.\n2. Select **Encode** to convert to Base64 or **Decode** to revert to plain text.\n3. The conversion happens **instantly** in your browser.',
    commonErrors: '- **Invalid Base64**: Ensure characters are only A-Z, a-z, 0-9, +, /, and =.\n- **Data Corruption**: Ensure you are not decoding binary files as plain text.',
  },
  {
    id: 'url-encode-decode',
    name: 'URL Encode/Decode',
    description: 'Encode and decode URL strings online',
    category: 'encoding',
    icon: '🔗',
    tags: ['url', 'encode', 'decode', 'percent', 'online'],
    popular: true,
    supportsShare: true,
    seoTitle: 'URL Encode & Decode — Percent Encoding | DevTools Online',
    seoDescription: 'URL-encode and percent-decode strings online. Encode special characters for query params or decode %XX sequences — free, instant, no login needed.',
  },
  {
    id: 'html-encode-decode',
    name: 'HTML Encode/Decode',
    description: 'Encode and decode HTML entities online',
    category: 'encoding',
    icon: '🏷️',
    tags: ['html', 'encode', 'decode', 'entities', 'online'],
    seoTitle: 'HTML Encode & Decode — HTML Entities | DevTools Online',
    seoDescription: 'Encode special characters to HTML entities and decode entities back to text online instantly. Free, secure tool to prevent XSS and ensure correct character rendering.',
    howToUse: '1. **Paste** your plain text or HTML code into the input area.\n2. **Select** between "Encode" or "Decode" modes.\n3. The conversion happens **instantly** in your browser.\n4. **Copy** the converted string for use in your web projects.',
    commonErrors: '- **Double Encoding**: Avoid encoding an already encoded string to prevent display bugs.\n- **Incomplete Entities**: Ensure entities start with `&` and end with `;` for proper decoding.',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and inspect JSON Web Tokens online',
    category: 'encoding',
    icon: '🎫',
    tags: ['jwt', 'token', 'decode', 'auth', 'online'],
    popular: true,
    supportsShare: true,
    seoTitle: 'JWT Decoder — Decode JSON Web Tokens | DevTools Online',
    seoDescription: 'Decode and inspect JSON Web Tokens online. View header, payload & signature, check expiry, validate structure — no key required, runs in browser.',
  },

  // Crypto & Hash
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256, SHA512 hashes online',
    category: 'crypto',
    icon: '🔒',
    tags: ['hash', 'md5', 'sha1', 'sha256', 'sha512', 'crypto', 'online'],
    popular: true,
    supportsShare: true,
    seoDescription: 'Generate MD5, SHA-1, SHA-256 and SHA-512 hashes online instantly. Free tool to compute file checksums and hash text with 100% client-side security.',
    howToUse: '1. **Paste** your text or **drag and drop** a file into the input area.\n2. The tool will **instantly compute** hashes using multiple algorithms.\n3. **Compare** resulting hex strings to verify data integrity.\n4. **Copy** specific hashes (MD5, SHA-256, etc.) with a single click.',
    commonErrors: '- **Unsupported Files**: Extremely large files may slow down your browser as processing is entirely local.\n- **Encoding Issues**: Different input encodings (UTF-8 vs UTF-16) will result in different hash values.',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong, secure passwords online',
    category: 'crypto',
    icon: '🔑',
    tags: ['password', 'generator', 'security', 'random', 'online'],
    popular: true,
    seoDescription: 'Generate strong, cryptographically secure passwords online. Customize length and character sets (symbols, numbers, cases) with 100% local, no-server generation.',
    howToUse: '1. **Choose** your desired length (up to 128 characters).\n2. **Toggle** character sets: Uppercase, Lowercase, Numbers, and Symbols.\n3. **Add** specific characters to exclude if required.\n4. **Copy** your new secure password instantly.',
    commonErrors: '- **Complexity Warning**: Ensure you include symbols and numbers for high-entropy passwords.\n- **Clipboard Risks**: Always clear your clipboard after pasting your password into a secure manager.',
  },
  {
    id: 'bcrypt',
    name: 'BCrypt Hash',
    description: 'Generate and verify BCrypt password hashes online',
    category: 'crypto',
    icon: '🛡️',
    tags: ['bcrypt', 'hash', 'password', 'security', 'online'],
    new: true,
    seoDescription: 'Generate and verify BCrypt password hashes online. Securely test BCrypt salts and hash matching with 100% client-side processing for developer safety.',
    howToUse: '1. **Enter** the plain text password you want to hash or verify.\n2. **Set cost factor** (salt rounds) for generation (default is 10).\n3. **Input existing hash** to check if it matches the current text.\n4. **Generate** or verify results instantly in your browser.',
    commonErrors: '- **High Cost Factor**: Values above 12 may significantly slow down generation in some browsers.\n- **Invalid Format**: Ensure BCrypt hashes start with standard prefixes like `$2a$` or `$2b$`.',
  },

  // String
  {
    id: 'string-case-converter',
    name: 'Case Converter',
    description: 'Convert strings between camelCase, snake_case, PascalCase, kebab-case and more online',
    category: 'string',
    icon: '🔤',
    tags: ['string', 'case', 'camel', 'snake', 'pascal', 'kebab', 'online'],
    popular: true,
    supportsShare: true,
    seoTitle: 'String Case Converter — camelCase, snake_case & More | DevTools Online',
    seoDescription: 'Convert strings between camelCase, snake_case, PascalCase, kebab-case, SCREAMING_SNAKE and more — free online tool, instant bulk conversion.',
  },
  {
    id: 'text-diff',
    name: 'Text Diff',
    description: 'Find differences between two text blocks online',
    category: 'string',
    icon: '📝',
    tags: ['text', 'diff', 'compare', 'online'],
    seoTitle: 'Text Diff Tool — Compare Two Texts | DevTools Online',
    seoDescription: 'Find and highlight differences between two text blocks online. Side-by-side or inline diff view, line-by-line comparison — free, no signup needed.',
  },
  {
    id: 'lorem-ipsum',
    name: 'Lorem Ipsum',
    description: 'Generate Lorem Ipsum placeholder text online',
    category: 'string',
    icon: '📃',
    tags: ['lorem', 'ipsum', 'placeholder', 'text', 'generator', 'online'],
    seoTitle: 'Lorem Ipsum Generator — Placeholder Text | DevTools Online',
    seoDescription: 'Generate Lorem Ipsum placeholder text online — choose paragraphs, sentences or words, customize amount. Free, instant, no signup, copy with one click.',
  },
  {
    id: 'string-inspector',
    name: 'String Inspector',
    description: 'Analyze strings: length, word count, char frequency online',
    category: 'string',
    icon: '🔎',
    tags: ['string', 'analyze', 'count', 'inspect', 'online'],
    seoTitle: 'String Inspector & Analyzer | DevTools Online',
    seoDescription: 'Analyze any string online — length, word count, character frequency, byte size, unique chars. Free, instant, runs entirely in your browser.',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with live highlighting online',
    category: 'string',
    icon: '🎯',
    tags: ['regex', 'regexp', 'test', 'pattern', 'match', 'online'],
    popular: true,
    supportsShare: true,
    seoTitle: 'Regex Tester — Test Regular Expressions Live | DevTools Online',
    seoDescription: 'Test and debug regular expressions online with real-time match highlighting. Supports flags, capture groups, replace preview — free, no signup.',
  },

  // Number
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    description: 'Convert between binary, octal, decimal, and hexadecimal online',
    category: 'number',
    icon: '🔢',
    tags: ['number', 'binary', 'hex', 'octal', 'decimal', 'convert', 'online'],
    seoTitle: 'Number Base Converter — Binary, Hex, Octal | DevTools Online',
    seoDescription: 'Convert numbers between binary, octal, decimal and hexadecimal online — instant, free, no signup. Shows all bases simultaneously with copy buttons.',
  },
  {
    id: 'byte-converter',
    name: 'Byte / Size Converter',
    description: 'Convert between bytes, KB, MB, GB, TB online',
    category: 'number',
    icon: '💾',
    tags: ['bytes', 'kb', 'mb', 'gb', 'size', 'convert', 'online'],
    seoTitle: 'Byte / File Size Converter | DevTools Online',
    seoDescription: 'Convert between bytes, KB, MB, GB and TB online — instant, free, no signup. Supports decimal (SI) and binary (IEC) units side by side.',
  },

  // Date & Time
  {
    id: 'unix-timestamp',
    name: 'Unix Timestamp',
    description: 'Convert between Unix timestamps and human-readable dates online',
    category: 'datetime',
    icon: '📅',
    tags: ['unix', 'timestamp', 'date', 'time', 'convert', 'online'],
    popular: true,
    seoTitle: 'Unix Timestamp Converter — Epoch to Date | DevTools Online',
    seoDescription: 'Convert Unix epoch timestamps to readable dates and vice versa online — instant, free, no signup. Supports seconds, milliseconds and ISO 8601.',
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    description: 'Parse and explain cron job expressions online',
    category: 'datetime',
    icon: '⏰',
    tags: ['cron', 'schedule', 'expression', 'parse', 'online'],
    new: true,
    seoTitle: 'Cron Expression Parser & Explainer | DevTools Online',
    seoDescription: 'Parse and explain cron job expressions in plain English online — see next run times, validate syntax. Free, instant, no signup, runs in browser.',
  },

  // Web
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    description: 'Minify and compress CSS code online',
    category: 'web',
    icon: '🎨',
    tags: ['css', 'minify', 'compress', 'web', 'online'],
    seoTitle: 'CSS Minifier & Compressor | DevTools Online',
    seoDescription: 'Minify and compress CSS code online — remove whitespace, comments and optimize output. Free, instant, no signup, reduce stylesheet file size fast.',
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    description: 'Minify and compress HTML markup online',
    category: 'web',
    icon: '🌐',
    tags: ['html', 'minify', 'compress', 'web', 'online'],
    seoTitle: 'HTML Minifier & Compressor | DevTools Online',
    seoDescription: 'Minify and compress HTML markup online — remove whitespace, comments and optional attributes. Free, instant, no signup, reduce page size fast.',
  },
  {
    id: 'html-preview',
    name: 'HTML / CSS / JS Preview',
    description: 'Write HTML, CSS, and JavaScript and see the live preview instantly in your browser',
    category: 'web',
    icon: '🖥️',
    tags: ['html', 'css', 'javascript', 'js', 'preview', 'live', 'sandbox', 'playground', 'web', 'online'],
    new: true,
    seoTitle: 'HTML / CSS / JS Live Preview — Sandbox | DevTools Online',
    seoDescription: 'Write HTML, CSS and JavaScript and see a live preview instantly in your browser — free online sandbox, no setup, no signup, no server needed.',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Live preview of Markdown rendered to HTML online',
    category: 'web',
    icon: '📖',
    tags: ['markdown', 'preview', 'render', 'html', 'online'],
    popular: true,
    seoTitle: 'Markdown Live Preview — Rendered HTML | DevTools Online',
    seoDescription: 'Live Markdown editor with real-time HTML preview online. Supports GFM, tables, code blocks and task lists — copy HTML or download, no login needed.',
  },
  {
    id: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO meta tags for your website online',
    category: 'web',
    icon: '🏷️',
    tags: ['meta', 'seo', 'tags', 'html', 'generator', 'online'],
    new: true,
    seoTitle: 'SEO Meta Tag Generator | DevTools Online',
    seoDescription: 'Generate SEO meta tags for your website online — title, description, Open Graph, Twitter Card. Copy-ready HTML tags, free, no signup required.',
  },

  // Color
  {
    id: 'color-converter',
    name: 'Color Converter',
    description: 'Convert between HEX, RGB, HSL, and HSV color formats online',
    category: 'color',
    icon: '🎨',
    tags: ['color', 'hex', 'rgb', 'hsl', 'hsv', 'convert', 'online'],
    popular: true,
    seoTitle: 'Color Converter — HEX, RGB, HSL, HSV | DevTools Online',
    seoDescription: 'Convert colors between HEX, RGB, HSL and HSV formats instantly online. Click to pick a color and get all formats at once — free, no signup.',
  },
  {
    id: 'color-palette',
    name: 'Color Palette Generator',
    description: 'Generate beautiful color palettes and gradients online',
    category: 'color',
    icon: '🖌️',
    tags: ['color', 'palette', 'gradient', 'generator', 'online'],
    new: true,
    seoTitle: 'Color Palette Generator | DevTools Online',
    seoDescription: 'Generate beautiful color palettes and gradients online — complementary, triadic, analogous, monochromatic schemes. Free, copy HEX codes, no signup.',
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID v1, v4, and v7 identifiers online',
    category: 'generator',
    icon: '⚡',
    tags: ['uuid', 'guid', 'generate', 'id', 'random', 'online'],
    popular: true,
    seoTitle: 'UUID Generator — v1, v4, v7 UUIDs | DevTools Online',
    seoDescription: 'Generate RFC-compliant UUID v1, v4 and v7 identifiers online — bulk generation, copy with one click. Cryptographically random, 100% client-side.',
  },
  {
    id: 'random-string',
    name: 'Random String Generator',
    description: 'Generate random strings with custom length and charset online',
    category: 'generator',
    icon: '🎲',
    tags: ['random', 'string', 'generator', 'token', 'online'],
    seoTitle: 'Random String Generator — Custom Charset & Length | DevTools Online',
    seoDescription: 'Generate random strings with custom length and character set online — alphanumeric, hex, base64, custom. Bulk generation, free, no signup needed.',
  },

  // Formatters
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries online — free SQL formatter',
    category: 'formatter',
    icon: '🗄️',
    tags: ['sql', 'format', 'query', 'database', 'online', 'beautify'],
    supportsShare: true,
    seoTitle: 'SQL Formatter & Beautifier | DevTools Online',
    seoDescription: 'Format and beautify SQL queries online — supports MySQL, PostgreSQL, SQL Server, T-SQL. Configurable indentation, keyword case — free, no signup.',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description: 'Format and validate XML documents online',
    category: 'formatter',
    icon: '📄',
    tags: ['xml', 'format', 'validate', 'beautify', 'online'],
    seoTitle: 'XML Formatter & Validator | DevTools Online',
    seoDescription: 'Format and validate XML documents online — beautify with proper indentation, detect syntax errors. Free, instant, no signup, supports large files.',
  },
  {
    id: 'graphql-formatter',
    name: 'GraphQL Formatter',
    description: 'Format and beautify GraphQL queries and schemas online',
    category: 'formatter',
    icon: '🔮',
    tags: ['graphql', 'format', 'beautify', 'query', 'schema', 'online'],
    new: true,
    supportsShare: true,
    suggestedTools: ['json-formatter', 'js-formatter'],
    seoTitle: 'GraphQL Formatter & Beautifier | DevTools Online',
    seoDescription: 'Format and beautify GraphQL queries and schemas online — improve readability with proper indentation. Free, instant, no signup, runs entirely in your browser.',
    howToUse: '1. Paste your **GraphQL query or schema** into the editor.\n2. The tool will **auto-detect** the structure and format it.\n3. Use the **Copy** button to get the clean output.',
    commonErrors: '- **Syntax Errors**: Ensure you have correct opening/closing braces.\n- **Invalid Characters**: Hidden characters or smart quotes can break the parser.',
  },

  // Misc
  {
    id: 'image-to-base64',
    name: 'Image to Base64',
    description: 'Convert images to Base64 encoded data URLs online',
    category: 'misc',
    icon: '🖼️',
    tags: ['image', 'base64', 'convert', 'data-url', 'online'],
    seoTitle: 'Image to Base64 Converter | DevTools Online',
    seoDescription: 'Convert images to Base64 encoded data URLs online — drag and drop any image, copy data URI. Free, 100% client-side, no upload to server, no signup.',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Generate QR codes from text or URLs online',
    category: 'misc',
    icon: '📱',
    tags: ['qr', 'qrcode', 'generate', 'barcode', 'online'],
    seoTitle: 'QR Code Generator — URL, WiFi, vCard & More | DevTools Online',
    seoDescription: 'Generate QR codes from text, URLs, WiFi credentials, email, phone, SMS or vCard online — download PNG, free, no signup, customizable size.',
  },

  // ── New tools ──────────────────────────────────────────────────────────────

  // JSON (new)
  {
    id: 'yaml-json',
    name: 'YAML ↔ JSON',
    description: 'Convert between YAML and JSON formats online',
    category: 'json',
    icon: '📄',
    tags: ['yaml', 'json', 'convert', 'online'],
    new: true,
    seoTitle: 'YAML to JSON Converter Online (& JSON to YAML) | DevTools Online',
    seoDescription: 'Convert YAML to JSON or JSON to YAML online instantly. Free bidirectional conversion tool with syntax validation, formatting, and 100% browser-side processing.',
    howToUse: '1. **Paste** your YAML or JSON into the input box.\n2. The tool will **auto-detect** the format and perform the conversion.\n3. **Switch** between YAML to JSON or JSON to YAML modes as needed.\n4. **Copy** the result or download it directly.',
    commonErrors: '- **Indentation**: YAML is strict about spaces—ensure your formatting is consistent.\n- **Invalid Braces**: For JSON, check for any missing curly or square brackets.',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript',
    description: 'Generate TypeScript interfaces from JSON data online',
    category: 'json',
    icon: '🔷',
    tags: ['json', 'typescript', 'interface', 'type', 'generate', 'online'],
    new: true,
    seoTitle: 'JSON to TypeScript Interface Generator | DevTools Online',
    seoDescription: 'Generate TypeScript interfaces from JSON online instantly. Free tool to convert JSON objects into clean, production-ready TypeScript types and interfaces.',
    howToUse: '1. **Paste** your JSON sample into the editor.\n2. The tool will **instantly parse** and generate the interfaces.\n3. **Review** the nested types created for sub-objects.\n4. **Copy** the result directly into your TypeScript project.',
    commonErrors: '- **Malformed JSON**: Ensure your input is valid JSON before generating types.\n- **Empty Objects**: Empty objects in your JSON may result in blank interface definitions.',
  },
  {
    id: 'jsonpath-tester',
    name: 'JSONPath Tester',
    description: 'Test JSONPath expressions against JSON data interactively online',
    category: 'json',
    icon: '🎯',
    tags: ['jsonpath', 'json', 'query', 'path', 'filter', 'online'],
    new: true,
    seoTitle: 'JSONPath Tester & Query Tool | DevTools Online',
    seoDescription: 'Test JSONPath expressions against JSON data online with real-time results. Free interactive tool to query, filter, and extract data from JSON using path syntax.',
    howToUse: '1. **Paste** your JSON data into the source editor.\n2. **Type** your JSONPath expression (e.g., `$.items[*].id`) into the query field.\n3. **View results** as they update in real-time.\n4. **Debug** matching nodes with visual feedback.',
    commonErrors: '- **Unsupported Operators**: Ensure your query follows the standard JSONPath specification.\n- **Invalid Syntax**: Check for missing brackets or incorrect wildcards in your path.',
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema Validator',
    description: 'Validate JSON data against a JSON Schema online',
    category: 'json',
    icon: '✅',
    tags: ['json', 'schema', 'validate', 'jsonschema', 'online'],
    new: true,
    seoTitle: 'JSON Schema Validator | DevTools Online',
    seoDescription: 'Validate JSON data against JSON Schema (Draft 4 to 2020-12) online instantly. Free tool with detailed error messages, path highlighting, and zero data uploads.',
    howToUse: '1. **Paste** your JSON data into the "Data" input.\n2. **Paste** your JSON Schema into the "Schema" input.\n3. The tool will **instantly validate** and highlight specific error locations.\n4. **Correct** the issues based on the provided validation messages.',
    commonErrors: '- **Schema Version**: Ensure your $schema draft is supported by the validator.\n- **Circular References**: Some complex schemas with recursion may take longer to validate.',
  },

  // Encoding (new)
  {
    id: 'hex-encode-decode',
    name: 'Hex Encode/Decode',
    description: 'Encode text to hexadecimal or decode hex back to text online',
    category: 'encoding',
    icon: '🔢',
    tags: ['hex', 'hexadecimal', 'encode', 'decode', 'online'],
    new: true,
    seoTitle: 'Hex Encode & Decode | DevTools Online',
    seoDescription: 'Convert text to hexadecimal and decode hex strings back to plain text online instantly. Free, secure tool supporting UTF-8 and ASCII with 100% local processing.',
    howToUse: '1. **Type** or paste your text or hex blocks into the input.\n2. **Select** the desired conversion direction (Text ↔ Hex).\n3. **Use delimiters** (like spaces) to separate bytes if needed.\n4. **Copy** the resulting hex or text output.',
    commonErrors: '- **Illegal Hex Characters**: Only 0-9 and A-F are valid for hexadecimal input.\n- **Incomplete Bytes**: Each byte is represented by two hex characters; odd-length inputs may fail.',
  },
  {
    id: 'binary-encode-decode',
    name: 'Binary Encode/Decode',
    description: 'Encode text to binary bits or decode binary back to text online',
    category: 'encoding',
    icon: '💻',
    tags: ['binary', 'bits', 'encode', 'decode', 'online'],
    new: true,
    seoTitle: 'Binary Encode & Decode | DevTools Online',
    seoDescription: 'Convert any text to binary bits (0s and 1s) and decode binary back to text online instantly. Free tool with 8-bit spacing for high readability and security.',
    howToUse: '1. **Enter** your string or binary bitstream in the input editor.\n2. **Choose** between "Text to Binary" or "Binary to Text" modes.\n3. **Observe** the bits update with optional byte-spacing.\n4. **Copy** the final result for your documentation or code.',
    commonErrors: '- **Input Noise**: Ensure binary input for decoding contains only 0s, 1s, and spaces.\n- **Padding**: For text conversion, every character usually requires 8 bits of binary data.',
  },

  // String (new)
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    description: 'Convert text to URL-friendly slugs with custom options online',
    category: 'string',
    icon: '🔗',
    tags: ['slug', 'url', 'permalink', 'string', 'seo', 'online'],
    new: true,
    seoTitle: 'Slug Generator — URL-Friendly Slugs | DevTools Online',
    seoDescription: 'Convert text to URL-friendly slugs online — customize separator, case, remove stop words. Free, instant, perfect for SEO-friendly URLs and permalinks.',
  },
  {
    id: 'string-escape',
    name: 'String Escape/Unescape',
    description: 'Escape and unescape strings for JS, JSON, HTML, Regex, and URL online',
    category: 'string',
    icon: '🔧',
    tags: ['escape', 'unescape', 'string', 'js', 'json', 'html', 'regex', 'online'],
    new: true,
    seoTitle: 'String Escape / Unescape — JS, JSON, HTML, Regex | DevTools Online',
    seoDescription: 'Escape and unescape strings for JavaScript, JSON, HTML, Regex and URL encoding online — free, instant, no signup, runs entirely in browser.',
  },
  {
    id: 'html-to-markdown',
    name: 'HTML to Markdown',
    description: 'Convert HTML markup to clean Markdown syntax online',
    category: 'string',
    icon: '📝',
    tags: ['html', 'markdown', 'convert', 'md', 'online'],
    new: true,
    seoTitle: 'HTML to Markdown Converter | DevTools Online',
    seoDescription: 'Quickly convert HTML to clean, readable Markdown online. Perfect for developers and content creators seeking an instant, software-free way to transform HTML markup.',
    howToUse: '1. **Paste** your HTML code into the input box.\n2. The tool will **instantly convert** it into Markdown format.\n3. **Copy the output** or download the result.\n\nThis HTML to Markdown converter works entirely in your browser, ensuring fast and secure processing.',
    commonErrors: '- **Malformed HTML**: Ensure your input has valid opening and closing tags.\n- **Complex JS/CSS**: Scripts and styles are stripped as they are not valid Markdown.',
  },

  // Date & Time (new)
  {
    id: 'timezone-converter',
    name: 'Timezone Converter',
    description: 'Convert time between different timezones around the world online',
    category: 'datetime',
    icon: '🌍',
    tags: ['timezone', 'time', 'convert', 'utc', 'dst', 'world', 'online'],
    new: true,
    seoTitle: 'Timezone Converter — Convert Time Zones Instantly | DevTools Online',
    seoDescription: 'Convert time between any two timezones online — supports all IANA zones, DST-aware, shows UTC offset. Free, instant, no signup required.',
  },
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    description: 'Calculate difference between dates or add/subtract time online',
    category: 'datetime',
    icon: '🗓️',
    tags: ['date', 'calculator', 'difference', 'days', 'add', 'subtract', 'online'],
    new: true,
    seoTitle: 'Date Calculator — Difference & Add/Subtract Days | DevTools Online',
    seoDescription: 'Calculate the difference between two dates or add/subtract days, months and years online — free, instant, no signup, works in your browser.',
  },

  // Web (new)
  {
    id: 'css-formatter',
    name: 'CSS Formatter',
    description: 'Beautify or minify CSS code online',
    category: 'web',
    icon: '✨',
    tags: ['css', 'format', 'beautify', 'minify', 'web', 'online'],
    new: true,
    seoTitle: 'CSS Formatter & Beautifier | DevTools Online',
    seoDescription: 'Beautify or minify CSS code online — format with proper indentation, organize properties. Free, instant, no signup, supports modern CSS syntax.',
  },
  {
    id: 'js-formatter',
    name: 'JS Minifier / Formatter',
    description: 'Minify or beautify JavaScript code online',
    category: 'web',
    icon: '⚡',
    tags: ['javascript', 'js', 'minify', 'format', 'beautify', 'online'],
    new: true,
    seoTitle: 'JavaScript Minifier & Formatter | DevTools Online',
    seoDescription: 'Minify or beautify JavaScript code online — format with Prettier-style indentation or compress for production. Free, instant, no signup required.',
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    description: 'Parse a URL into its components: protocol, host, path, query params online',
    category: 'web',
    icon: '🔍',
    tags: ['url', 'parse', 'query', 'params', 'host', 'path', 'online'],
    new: true,
    seoTitle: 'URL Parser — Analyze URL Components | DevTools Online',
    seoDescription: 'Parse any URL into its components — protocol, host, path, query parameters, hash — online. Free, instant, no signup, copy individual parts easily.',
  },

  // Formatters (new)
  {
    id: 'yaml-formatter',
    name: 'YAML Formatter',
    description: 'Format and validate YAML documents online',
    category: 'formatter',
    icon: '📋',
    tags: ['yaml', 'format', 'validate', 'beautify', 'online'],
    new: true,
    seoTitle: 'YAML Formatter & Validator | DevTools Online',
    seoDescription: 'Format and validate YAML documents online — detect syntax errors, normalize indentation, view structure. Free, instant, no signup, runs in browser.',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV data to JSON array with auto-detect delimiter online',
    category: 'formatter',
    icon: '📊',
    tags: ['csv', 'json', 'convert', 'table', 'data', 'online'],
    new: true,
    seoTitle: 'CSV to JSON Converter | DevTools Online',
    seoDescription: 'Convert CSV data to JSON array online — auto-detect delimiter, custom headers, type inference. Free, instant, no signup, copy or download output.',
  },

  // Misc (new)
  {
    id: 'chmod-calculator',
    name: 'Chmod Calculator',
    description: 'Calculate Unix file permissions from octal or symbolic notation online',
    category: 'misc',
    icon: '🔐',
    tags: ['chmod', 'unix', 'linux', 'permissions', 'octal', 'rwx', 'online'],
    new: true,
    seoTitle: 'Chmod Calculator — Unix File Permissions | DevTools Online',
    seoDescription: 'Calculate Unix file permissions from octal or symbolic notation online. Convert rwxr-xr-x to 755 and vice versa — free, instant, no signup needed.',
  },

  // Crypto (new)
  {
    id: 'jwt-encoder',
    name: 'JWT Encoder',
    description: 'Create and sign JSON Web Tokens with HS256/HS384/HS512 online',
    category: 'crypto',
    icon: '🎟️',
    tags: ['jwt', 'token', 'encode', 'sign', 'hmac', 'auth', 'online'],
    new: true,
    seoDescription: 'Create and sign JSON Web Tokens (JWT) online with HS256, HS384, or HS512 algorithms. Free interactive tool to build and test secure tokens locally.',
    howToUse: '1. **Modify** the Header and Payload JSON structures as needed.\n2. **Enter your secret key** for HMAC signature algorithms.\n3. **Set expiry (exp)** or other claims directly in the JSON payload.\n4. **Download** or copy the encoded and signed JWT string.',
    commonErrors: '- **Weak Secret**: Using short or guessable secrets makes tokens vulnerable to brute-force.\n- **Invalid JSON**: Ensure both header and payload are well-formed JSON objects.',
  },

  // Converter
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert images between JPG, PNG, WebP, and BMP formats online',
    category: 'converter',
    icon: '🖼️',
    tags: ['image', 'convert', 'jpg', 'png', 'webp', 'bmp', 'online'],
    new: true,
    seoTitle: 'Image Converter — JPG, PNG, WebP, BMP | DevTools Online',
    seoDescription: 'Convert images between JPG, PNG, WebP and BMP formats online — 100% client-side, no upload to server. Free, instant, no signup, preserves quality.',
    howToUse: '1. **Upload** your source image (JPG, PNG, WebP, or BMP).\n2. **Select** the target format from the dropdown menu.\n3. **Download** the converted image instantly.\n4. **Repeat** to convert more files; your privacy is protected as all processing is local.',
    commonErrors: '- **Corrupt Buffer**: Ensure the source file is not corrupt and is a valid image.\n- **Browser Memory**: Extremely large files might crash the browser; try reducing size first.',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize and compress images with quality control online',
    category: 'converter',
    icon: '📐',
    tags: ['image', 'resize', 'compress', 'quality', 'scale', 'online'],
    new: true,
    seoTitle: 'Image Resizer — Resize & Compress Images | DevTools Online',
    seoDescription: 'Resize and compress images online with quality control — set exact dimensions or scale by percentage. Free, 100% client-side, no signup required.',
    howToUse: '1. **Drag and drop** your image into the resize area.\n2. **Specify** the target width or height (aspect ratio is preserved by default).\n3. **Adjust** the quality slider if you need to reduce file size.\n4. **Download** the resized and optimized version of your image.',
    commonErrors: '- **Very Small Dimensions**: Resizing to 1x1 or empty dimensions may result in a black image.\n- **High Compression**: Setting quality below 50% may result in visible artifacts.',
  },
  {
    id: 'svg-to-png',
    name: 'SVG to PNG / JPG',
    description: 'Convert SVG vector files to rasterized PNG or JPG images online',
    category: 'converter',
    icon: '✏️',
    tags: ['svg', 'png', 'jpg', 'convert', 'rasterize', 'vector', 'online'],
    new: true,
    seoTitle: 'SVG to PNG / JPG Converter | DevTools Online',
    seoDescription: 'Convert SVG vector files to rasterized PNG or JPG images online — set custom resolution, download instantly. Free, 100% client-side, no signup.',
    howToUse: '1. **Paste** your SVG code or **upload** an .svg file.\n2. **Set** the output width and height (rasterization resolution).\n3. **Select** between PNG (transparent) or JPG (white background) format.\n4. **Download** your new raster image; all rendering is done locally.',
    commonErrors: '- **Complex Gradients**: Some advanced SVG patterns might render differently depending on your browser.\n- **External Resources**: SVGs with links to external assets may not render correctly due to security limits.',
  },
  {
    id: 'csv-to-excel',
    name: 'CSV to Excel',
    description: 'Convert CSV files to Excel XLSX spreadsheet format online',
    category: 'converter',
    icon: '📊',
    tags: ['csv', 'excel', 'xlsx', 'convert', 'spreadsheet', 'online'],
    new: true,
    seoTitle: 'CSV to Excel Converter — Download XLSX | DevTools Online',
    seoDescription: 'Convert CSV files to Excel XLSX spreadsheet format online — instant download, no signup, 100% client-side. Free online CSV to Excel converter.',
    howToUse: '1. **Select** or drop your `.csv` file into the converter.\n2. **Preview** the data table to ensure the encoding and delimiters are correct.\n3. **Download** the generated `.xlsx` file for use in Microsoft Excel or Google Sheets.\n4. **Safe and Private**: Your spreadsheet data never leaves your browser.',
    commonErrors: '- **Malformed Rows**: Lines with inconsistent column counts may be shifted.\n- **Special Characters**: If your data shows weird symbols, ensure your CSV uses UTF-8 encoding.',
  },
  {
    id: 'json-to-excel',
    name: 'JSON to Excel',
    description: 'Export JSON array data to Excel XLSX spreadsheet online',
    category: 'converter',
    icon: '📋',
    tags: ['json', 'excel', 'xlsx', 'convert', 'spreadsheet', 'export', 'online'],
    new: true,
    seoTitle: 'JSON to Excel Converter — Export XLSX | DevTools Online',
    seoDescription: 'Export JSON array data to Excel XLSX spreadsheet online — instant download, free, no signup, 100% client-side. Handles nested objects and arrays.',
    howToUse: '1. **Paste** your JSON array into the input editor.\n2. **Confirm** that the tool flattened the nested properties into table columns.\n3. **Download** the resulting Excel (.xlsx) file immediately.\n4. **Process locally**: Your sensitive data remains completely private.',
    commonErrors: '- **Non-Array Data**: JSON should be an array of objects for best Excel table conversion.\n- **JSON Errors**: Ensure your input is valid JSON first using our formatter.',
  },
  {
    id: 'markdown-to-html',
    name: 'Markdown to HTML',
    description: 'Convert Markdown to styled HTML and download as a file online',
    category: 'converter',
    icon: '📝',
    tags: ['markdown', 'html', 'convert', 'export', 'md', 'online'],
    new: true,
    seoTitle: 'Markdown to HTML Converter | DevTools Online',
    seoDescription: 'Convert Markdown to styled HTML online — download as .html file, copy code, preview output. Free, instant, supports GFM tables and task lists.',
    howToUse: '1. **Paste** your Markdown text into the left editor.\n2. **Check** the live preview on the right for correct formatting.\n3. **Copy** the raw HTML or **download** a fully styled `.html` document.\n4. Supports GFM (GitHub Flavored Markdown) including tables and checkboxes.',
    commonErrors: '- **Incomplete Tags**: Ensure HTML blocks inside Markdown are properly closed.\n- **Indentation**: Incorrect spacing in list items can break formatting in some renderers.',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Render HTML content and export to PDF via browser print online',
    category: 'converter',
    icon: '📄',
    tags: ['html', 'pdf', 'convert', 'print', 'export', 'online'],
    new: true,
    seoTitle: 'HTML to PDF Converter | DevTools Online',
    seoDescription: 'Render HTML content and export to PDF via browser print online — supports custom CSS, images. Free, no signup, works in any modern browser.',
    howToUse: '1. **Paste** your HTML or the website code you want to save.\n2. **Preview** the layout in the interactive frame.\n3. **Click Download PDF** to trigger the browser print-to-pdf engine.\n4. **Customize**: You can modify styles directly before exporting.',
    commonErrors: '- **Broken Images**: Ensure image URLs are valid or use base64 data URIs.\n- **Dynamic Content**: Scripts might not execute fully before the PDF generation starts.',
  },

  // String (new batch 2)
  { id: 'text-sorter', name: 'Text Sorter', description: 'Sort, deduplicate, reverse and shuffle text lines online', category: 'string', icon: '📑', tags: ['text', 'sort', 'deduplicate', 'lines', 'shuffle', 'online'], new: true, seoTitle: 'Text Line Sorter & Deduplicator | DevTools Online', seoDescription: 'Sort, deduplicate, reverse and shuffle text lines online — alphabetical, numerical, by length or random order. Free, instant, no signup needed.' },
  { id: 'word-frequency', name: 'Word Frequency', description: 'Count word and character frequency in text online', category: 'string', icon: '📊', tags: ['word', 'frequency', 'count', 'text', 'analyze', 'online'], new: true, seoTitle: 'Word Frequency Counter | DevTools Online', seoDescription: 'Count word and character frequency in any text online — ranked list with counts and percentages. Free, instant, no signup, 100% in-browser.' },
  { id: 'text-stats', name: 'Text Statistics', description: 'Detailed text stats: reading time, sentences, paragraphs online', category: 'string', icon: '📈', tags: ['text', 'statistics', 'reading', 'time', 'words', 'sentences', 'online'], new: true, seoTitle: 'Text Statistics & Readability Tool | DevTools Online', seoDescription: 'Get detailed text statistics online — word count, sentence count, reading time, paragraphs, Flesch score. Free, instant, runs in your browser.' },

  // JSON (new batch 2)
  { id: 'json-to-code', name: 'JSON to Code', description: 'Generate Python, PHP, Go, Ruby, Java code from JSON online', category: 'json', icon: '💻', tags: ['json', 'code', 'python', 'php', 'go', 'ruby', 'generate', 'online'], new: true, seoTitle: 'JSON to Code Generator — Python, PHP, Go & More | DevTools Online',
    seoDescription: 'Convert JSON objects to class/struct definitions for Python, PHP, Go, Ruby, and Java instantly. Free online code scaffolding tool with 100% browser-side processing.',
    howToUse: '1. **Paste** your JSON sample into the source editor.\n2. **Select** your target language (Python, Java, Go, etc.).\n3. **Scaffold** your classes or data structures automatically.\n4. **Copy** the generated code directly into your source files.',
    commonErrors: '- **Invalid JSON**: The tool requires a well-formed JSON object to detect structures.\n- **Mixed Types**: Arrays with inconsistent data types may result in "generic" object types.',
  },

  // Crypto (new batch 2)
  { id: 'aes-encrypt', name: 'AES Encrypt / Decrypt', description: 'Encrypt and decrypt text using AES-256-GCM in the browser online', category: 'crypto', icon: '🛡️', tags: ['aes', 'encrypt', 'decrypt', 'crypto', 'security', 'cipher', 'online'], new: true, seoTitle: 'AES-256 Encrypt & Decrypt | DevTools Online',
    seoDescription: 'Encrypt and decrypt text using AES-256-GCM online instantly. Secure, browser-based cipher with adjustable key/passphrase and zero data persistence.',
    howToUse: '1. **Select** operation: Encrypt or Decrypt.\n2. **Enter your secret key** or passphrase.\n3. **Input text** (plain for encryption, hex/base64 for decryption).\n4. **Process** and copy results; your key is never transmitted.',
    commonErrors: '- **Wrong Key**: AES is symmetric; the same key is required for encryption and decryption.\n- **Salt Mismatch**: Custom IVs or salts must match exactly for successful decryption.',
  },
  { id: 'totp-generator', name: 'TOTP / 2FA Generator', description: 'Generate and verify time-based one-time passwords (RFC 6238) online', category: 'crypto', icon: '🔑', tags: ['totp', '2fa', 'otp', 'authenticator', 'mfa', 'google', 'online'], new: true, seoTitle: 'TOTP / 2FA Code Generator — RFC 6238 | DevTools Online',
    seoDescription: 'Generate and verify 2FA TOTP codes (RFC 6238) online. Test Google Authenticator secrets and verify time-based tokens with 100% local processing.',
    howToUse: '1. **Paste your secret key** (usually Base32 format from an auth app).\n2. **Observe** the generated 6/8-digit code update every 30 seconds.\n3. **Verify** codes against your system clock to ensure sync.\n4. **Debug** interval states and HMAC internal properties.',
    commonErrors: '- **Clock Desync**: TOTP relies on accurate time; sync your system clock if codes fail.\n- **Invalid Secret**: Ensure your secret is a valid Base32 encoded string.',
  },

  // Number (new batch 2)
  { id: 'unit-converter', name: 'Unit Converter', description: 'Convert between units: length, weight, temperature, area, speed online', category: 'number', icon: '📏', tags: ['unit', 'convert', 'length', 'weight', 'temperature', 'area', 'speed', 'online'], new: true, seoTitle: 'Unit Converter — Length, Weight, Temperature & More | DevTools Online', seoDescription: 'Convert between units of length, weight, temperature, area and speed online — free, instant, no signup. All conversions run in your browser.' },
  { id: 'math-evaluator', name: 'Math Evaluator', description: 'Evaluate mathematical expressions with variables and functions online', category: 'number', icon: '🧮', tags: ['math', 'calculator', 'expression', 'evaluate', 'formula', 'online'], new: true, seoTitle: 'Math Expression Evaluator | DevTools Online', seoDescription: 'Evaluate mathematical expressions with variables and functions online — supports trig, log, constants. Free, instant, no signup, runs in browser.' },

  // Color (new batch 2)
  { id: 'css-gradient', name: 'CSS Gradient Generator', description: 'Visually build linear, radial, and conic CSS gradients online', category: 'color', icon: '🌈', tags: ['css', 'gradient', 'linear', 'radial', 'color', 'generator', 'online'], new: true, seoTitle: 'CSS Gradient Generator — Linear, Radial, Conic | DevTools Online', seoDescription: 'Visually build linear, radial and conic CSS gradients online — real-time preview, copy CSS code. Free, no signup, supports all modern gradient types.' },
  { id: 'css-shadow', name: 'CSS Shadow Generator', description: 'Visually build box-shadow and text-shadow CSS values online', category: 'color', icon: '🌑', tags: ['css', 'shadow', 'box-shadow', 'text-shadow', 'generator', 'online'], new: true, seoTitle: 'CSS Shadow Generator — box-shadow & text-shadow | DevTools Online', seoDescription: 'Visually build box-shadow and text-shadow CSS values online — real-time preview, copy CSS property. Free, no signup, supports multiple layers.' },

  // Web (new batch 2)
  { id: 'http-status-codes', name: 'HTTP Status Codes', description: 'Searchable reference for all HTTP status codes with descriptions online', category: 'web', icon: '🌐', tags: ['http', 'status', 'codes', '404', '200', '500', 'reference', 'online'], new: true, seoTitle: 'HTTP Status Codes Reference — All 1xx–5xx | DevTools Online', seoDescription: 'Searchable reference for all HTTP status codes with descriptions and examples online — 1xx, 2xx, 3xx, 4xx, 5xx. Free, instant, no signup needed.' },
  { id: 'mime-types', name: 'MIME Types Lookup', description: 'Look up MIME types by file extension or content type online', category: 'web', icon: '📂', tags: ['mime', 'type', 'extension', 'content-type', 'file', 'online'], new: true, seoTitle: 'MIME Types Lookup — File Extension to Content-Type | DevTools Online', seoDescription: 'Look up MIME types by file extension or content-type header online — comprehensive database. Free, instant, no signup, works in any browser.' },
  { id: 'curl-to-code', name: 'Curl to Code', description: 'Convert curl commands to fetch, axios, or Python requests code online', category: 'web', icon: '⚡', tags: ['curl', 'fetch', 'axios', 'python', 'http', 'convert', 'online'], new: true, seoTitle: 'Curl to Code Converter — fetch, axios, Python | DevTools Online', seoDescription: 'Convert curl commands to fetch, axios, Python requests or PHP code online — instant, free, no signup. Great for API integration and code generation.' },

  // Generator (new batch 2)
  { id: 'data-faker', name: 'Data Faker', description: 'Generate realistic fake test data: names, emails, phones, addresses online', category: 'generator', icon: '🎭', tags: ['fake', 'data', 'faker', 'test', 'name', 'email', 'phone', 'mock', 'online'], new: true, seoTitle: 'Fake Data Generator — Names, Emails, Addresses | DevTools Online', seoDescription: 'Generate realistic fake test data online — names, emails, phones, addresses, companies, up to 1000 rows. Free, no signup, export as JSON or CSV.' },

  // Generator (original)
  {
    id: 'nanoid-generator',
    name: 'Nano ID / ULID',
    description: 'Generate compact unique identifiers: Nano IDs and ULIDs online',
    category: 'generator',
    icon: '🆔',
    tags: ['nanoid', 'ulid', 'id', 'generate', 'unique', 'random', 'online'],
    new: true,
    seoTitle: 'Nano ID & ULID Generator | DevTools Online',
    seoDescription: 'Generate compact unique identifiers online — Nano IDs (URL-safe) and ULIDs (sortable). Custom alphabet, configurable length, free, no signup.',
  },

  // Batch 4 - Text/Code
  { id: 'html-formatter', name: 'HTML Formatter', description: 'Beautify and format HTML markup with proper indentation online', category: 'web', icon: '🖊️', tags: ['html', 'format', 'beautify', 'indent', 'web', 'online'], new: true, seoTitle: 'HTML Formatter & Beautifier | DevTools Online', seoDescription: 'Beautify and format HTML markup with proper indentation online — configurable indent size, attributes formatting. Free, instant, no signup required.' },
  { id: 'csv-viewer', name: 'CSV Viewer', description: 'View and explore CSV data as an interactive table with sorting online', category: 'formatter', icon: '📋', tags: ['csv', 'table', 'viewer', 'sort', 'filter', 'data', 'online'], new: true, seoTitle: 'CSV Viewer — Interactive Table with Sort & Filter | DevTools Online', seoDescription: 'View and explore CSV data as an interactive sortable table online — click headers to sort, search rows. Free, no signup, handles large CSV files.' },
  { id: 'env-parser', name: '.ENV Parser', description: 'Parse .env files to JSON and convert back, view key/value pairs online', category: 'misc', icon: '🔑', tags: ['env', 'dotenv', 'environment', 'json', 'config', 'parse', 'online'], new: true, seoTitle: '.ENV File Parser — ENV to JSON | DevTools Online', seoDescription: 'Parse .env files to JSON and convert back online — view key/value pairs, handle comments, multi-line values. Free, instant, no signup, client-side.' },
  { id: 'markdown-table', name: 'Markdown Table Generator', description: 'Create Markdown tables from a visual grid editor online', category: 'string', icon: '📊', tags: ['markdown', 'table', 'generator', 'md', 'grid', 'online'], new: true, seoTitle: 'Markdown Table Generator | DevTools Online', seoDescription: 'Create Markdown tables from a visual grid editor online — add rows, columns, align cells, copy formatted Markdown. Free, no signup, instant output.' },

  // Batch 4 - Web/Network
  { id: 'cidr-calculator', name: 'CIDR / IP Calculator', description: 'Calculate subnet, broadcast address, host range from CIDR notation online', category: 'web', icon: '🌐', tags: ['cidr', 'ip', 'subnet', 'network', 'calculator', 'ipv4', 'online'], new: true, seoTitle: 'CIDR / Subnet Calculator — IPv4 Network Tool | DevTools Online', seoDescription: 'Calculate subnet, broadcast address, host range and IP count from CIDR notation online. Free, instant, no signup — supports all IPv4 subnets.' },
  { id: 'http-headers-builder', name: 'HTTP Security Headers', description: 'Build and understand CORS, CSP, HSTS and other security headers online', category: 'web', icon: '🔒', tags: ['http', 'headers', 'cors', 'csp', 'hsts', 'security', 'online'], new: true, seoTitle: 'HTTP Security Headers Builder — CORS, CSP, HSTS | DevTools Online', seoDescription: 'Build and understand CORS, CSP, HSTS and other HTTP security headers online. Visual builder with explanations — free, no signup, copy-ready output.' },
  { id: 'robots-txt', name: 'robots.txt Generator', description: 'Generate robots.txt file with GUI rule builder for crawlers online', category: 'web', icon: '🤖', tags: ['robots', 'txt', 'seo', 'crawler', 'sitemap', 'generator', 'online'], new: true, seoTitle: 'robots.txt Generator — SEO Crawler Rules | DevTools Online', seoDescription: 'Generate a robots.txt file with a GUI rule builder online — allow/disallow paths, add sitemaps, configure crawlers. Free, no signup, instant output.' },
  { id: 'sitemap-generator', name: 'Sitemap Generator', description: 'Generate XML sitemap from a list of URLs online', category: 'web', icon: '🗺️', tags: ['sitemap', 'xml', 'seo', 'url', 'generator', 'online'], new: true, seoTitle: 'XML Sitemap Generator | DevTools Online', seoDescription: 'Generate an XML sitemap from a list of URLs online — set priority, change frequency, last modified. Free, instant, no signup, downloadable output.' },

  // Batch 4 - Dev Tools
  { id: 'keycode-tester', name: 'KeyCode Tester', description: 'Test keyboard events and inspect key codes, modifiers, and event properties online', category: 'misc', icon: '⌨️', tags: ['keycode', 'keyboard', 'event', 'key', 'shortcut', 'test', 'online'], new: true, seoTitle: 'KeyCode Tester — Keyboard Event Inspector | DevTools Online', seoDescription: 'Test keyboard events and inspect key codes, key names, modifiers and event properties online. Free, no signup — identify any key instantly.' },
  { id: 'aspect-ratio', name: 'Aspect Ratio Calculator', description: 'Calculate and convert aspect ratios for images and video (16:9, 4:3...) online', category: 'number', icon: '📐', tags: ['aspect', 'ratio', 'resolution', 'image', 'video', '16:9', 'online'], new: true, seoTitle: 'Aspect Ratio Calculator — 16:9, 4:3 & Custom | DevTools Online', seoDescription: 'Calculate and convert aspect ratios for images and video online — compute missing dimension from width/height. Free, instant, supports any ratio.' },
  { id: 'number-formatter', name: 'Number Formatter', description: 'Format numbers with locale-aware separators, currency, and notation online', category: 'number', icon: '🔢', tags: ['number', 'format', 'locale', 'currency', 'thousand', 'separator', 'online'], new: true, seoTitle: 'Number Formatter — Locale, Currency & Notation | DevTools Online', seoDescription: 'Format numbers with locale-aware separators, currency symbols and scientific notation online — free, instant, no signup, supports all locales.' },
  { id: 'ts-to-js', name: 'TypeScript → JavaScript', description: 'Strip TypeScript types and transpile TS to plain JavaScript online', category: 'web', icon: '🟡', tags: ['typescript', 'javascript', 'ts', 'js', 'transpile', 'convert', 'online'], new: true, seoTitle: 'TypeScript to JavaScript Transpiler | DevTools Online', seoDescription: 'Strip TypeScript types and transpile TS to plain JavaScript online — instant, free, no signup. Supports modern TypeScript syntax and decorators.' },
  {
    id: 'benchmark-builder',
    name: 'JS / TS Benchmark Builder',
    description: 'Compare execution speed of different JavaScript and TypeScript code snippets online',
    category: 'web',
    icon: '⏱️',
    tags: ['benchmark', 'performance', 'js', 'ts', 'javascript', 'typescript', 'speed', 'test', 'online'],
    new: true,
    seoTitle: 'JS / TS Benchmark Builder — Performance Comparison Tool | DevTools Online',
    seoDescription: 'Compare execution speed of different JavaScript and TypeScript code snippets online. Real-time benchmarking with ops/sec, iterations, and comparison — free, no signup.',
    howToUse: '1. Add multiple **test cases** to compare.\n2. Write your **Setup code** if needed for all cases.\n3. Click **Run Benchmark** and wait for the results (Ops/sec).',
    commonErrors: '- **Micro-benchmarking**: Ensure your tests run long enough to get stable results.\n- **External dependencies**: Cannot use network-based modules in benchmarks.',
  },

  // Batch 4 - Media/Visual
  { id: 'favicon-generator', name: 'Favicon Generator', description: 'Generate favicons from emoji or text in multiple sizes online', category: 'generator', icon: '🎨', tags: ['favicon', 'icon', 'emoji', 'png', 'generator', 'website', 'online'], new: true, seoTitle: 'Favicon Generator — From Emoji or Text | DevTools Online', seoDescription: 'Generate favicons from emoji or text in multiple sizes (16x16 to 512x512) online — download PNG, free, no signup, instant browser-side generation.' },
  { id: 'barcode-generator', name: 'Barcode Generator', description: 'Generate EAN-13, Code128, and other barcode formats online', category: 'generator', icon: '🔲', tags: ['barcode', 'ean', 'code128', 'qr', 'scan', 'generator', 'online'], new: true, seoTitle: 'Barcode Generator — EAN-13, Code128 & More | DevTools Online', seoDescription: 'Generate EAN-13, Code128, Code39, UPC-A and other barcode formats online — download PNG, adjust size. Free, instant, no signup required.' },
  { id: 'image-compressor', name: 'Image Compressor', description: 'Compress and optimize images while preserving quality online', category: 'converter', icon: '📸', tags: ['image', 'compress', 'optimize', 'quality', 'size', 'jpg', 'png', 'online'], new: true, seoTitle: 'Image Compressor — Reduce Image File Size | DevTools Online', seoDescription: 'Compress and optimize images online while preserving quality — reduce file size for web. Free, 100% client-side, no upload to server, no signup.', 
    howToUse: '1. **Drag and drop** your JPEG or PNG images into the tool.\n2. **Adjust** the compression level to find the balance between size and quality.\n3. **Compare** the original and compressed file sizes in real-time.\n4. **Download** all your optimized images; no data is sent to any server.',
    commonErrors: '- **Aggressive Compression**: Setting quality too low can cause blurriness.\n- **Oversized Source**: Extremely high-res images can use substantial browser RAM.',
  },
  { id: 'image-metadata-modifier', name: 'Image Metadata Editor', description: 'View and edit EXIF, IPTC, and XMP metadata of JPEG images online', category: 'converter', icon: '🖼️', tags: ['image', 'exif', 'metadata', 'edit', 'iptc', 'xmp', 'online'], new: true, supportsShare: false, seoTitle: 'Online Image Metadata & EXIF Editor | DevTools Online', seoDescription: 'View and edit image metadata online — modify EXIF, IPTC, XMP, and GPS tags for JPEG images. Free, 100% client-side, no signup required.',
    howToUse: '1. **Upload** a JPEG image from your device.\n2. **View** current EXIF, IPTC, and XMP metadata in the sidebar.\n3. **Modify** or delete specific tags (e.g., Artist, GPS, Software).\n4. **Save & Download** the new image with the updated metadata preserved or removed.',
    commonErrors: '- **Non-JPEG Files**: This editor is currently optimized for `.jpg` and `.jpeg` formats.\n- **Read-Only Tags**: Some low-level system tags cannot be manually edited.',
  },

  // npm
  { id: 'npm-checker', name: 'npm Package Checker', description: 'Look up any npm package — version, downloads, bundle size, dependencies, and changelog online', category: 'web', icon: '📦', tags: ['npm', 'package', 'node', 'registry', 'bundle', 'dependencies', 'version', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Package data fetched from the npm registry (registry.npmjs.org). Package names you search are sent to their API.', seoTitle: 'npm Package Checker — Version, Size & Downloads | DevTools Online', seoDescription: 'Look up any npm package online — latest version, weekly downloads, bundle size, dependencies & changelog. Instant search, powered by npm registry.' },

  // SVG Icons
  { id: 'svg-icons', name: 'SVG Icon Browser', description: 'Search and browse 200,000+ icons from Heroicons, Lucide, Material, Tabler and more — copy SVG, JSX, or CDN link instantly online', category: 'web', icon: '🎨', tags: ['svg', 'icons', 'heroicons', 'lucide', 'material', 'tabler', 'iconify', 'design', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Icon data fetched from the Iconify CDN. Search queries are sent to their API.', seoTitle: 'SVG Icon Browser — 200,000+ Icons | DevTools Online', seoDescription: 'Search 200,000+ SVG icons from Heroicons, Lucide, Material Design, Tabler & more. Copy SVG, JSX or CDN link instantly — free online icon browser.' },

  // .NET / C#
  { id: 'json-to-csharp', name: 'JSON to C# Classes', description: 'Generate C# class definitions from JSON — supports nested objects, arrays, nullable types, Newtonsoft & System.Text.Json attributes online', category: 'dotnet', icon: '🔷', tags: ['csharp', 'dotnet', 'json', 'class', 'model', 'poco', 'dto', 'newtonsoft', 'c#', 'online'], popular: true, new: true, seoTitle: 'JSON to C# Class Generator | DevTools Online',
    seoDescription: 'Generate C# class definitions from JSON online instantly. Free tool supporting nested objects, arrays, nullable types, Newtonsoft, and System.Text.Json attributes.',
    howToUse: '1. **Paste** your JSON data into the editor.\n2. **Configure** options like Namespace, Class Name, and property attributes.\n3. **Generate** the C# code instantly.\n4. **Copy** the resulting classes into your .NET project.',
    commonErrors: '- **Invalid JSON**: Ensure your input is well-formed JSON.\n- **Complex Types**: Highly irregular JSON structures may require manual adjustment of generated types.',
  },
  { id: 'nuget-checker', name: 'NuGet Package Checker', description: 'Search NuGet packages — version history, download stats, install commands, PackageReference snippets online', category: 'dotnet', icon: '📦', tags: ['nuget', 'package', 'dotnet', 'csharp', 'c#', '.net', 'library', 'dependency', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Package data fetched from api.nuget.org. Package names you search are sent to their API.', seoTitle: 'NuGet Package Checker | DevTools Online',
    seoDescription: 'Search NuGet packages online to view version history, download statistics, and installation commands. Free tool powered by the official NuGet API.',
    howToUse: '1. **Type** the package name (e.g., Newtonsoft.Json) into the search bar.\n2. **Select** the correct package from the results.\n3. **Explore** versions, dependencies, and download trends.\n4. **Copy** the installation command or PackageReference snippet.',
    commonErrors: '- **Network Issues**: Data is fetched directly from NuGet; intermittent API downtime may affect results.',
  },
  { id: 'connection-string-builder', name: 'Connection String Builder', description: 'Build database connection strings for SQL Server, MySQL, PostgreSQL, SQLite, Oracle and MongoDB with live preview online', category: 'dotnet', icon: '🔌', tags: ['connection', 'string', 'sql', 'server', 'mysql', 'postgresql', 'sqlite', 'oracle', 'mongodb', 'ef', 'dotnet', 'online'], popular: true, new: true, seoTitle: 'Connection String Builder — SQL Server, MySQL & More | DevTools Online',
    seoDescription: 'Build database connection strings for SQL Server, MySQL, PostgreSQL, SQLite, Oracle, and MongoDB online. Free interactive builder with live preview and security tips.',
    howToUse: '1. **Select** your database engine (e.g., SQL Server).\n2. **Enter** server details, database name, and credentials.\n3. **Toggle** options like Trust Server Certificate or Connection Pooling.\n4. **Copy** the generated connection string.',
    commonErrors: '- **Security Risk**: Avoid hardcoding plain-text passwords in persistent configuration files.',
  },
  { id: 'csharp-string-escape', name: 'C# String Escape', description: 'Escape/unescape C# strings — regular, verbatim @"..." and interpolated $"..." string formats online', category: 'dotnet', icon: '✏️', tags: ['csharp', 'c#', 'string', 'escape', 'verbatim', 'interpolated', 'dotnet', 'online'], new: true, seoTitle: 'C# String Escape / Unescape | DevTools Online',
    seoDescription: 'Escape and unescape C# strings online instantly. Supports regular, verbatim (@"..."), and interpolated ($"...") formats with 100% client-side processing.',
    howToUse: '1. **Paste** your C# string or plain text into the input.\n2. **Choose** between Escape or Unescape operations.\n3. **Select** the string type (Normal, Verbatim, or Interpolated).\n4. **Copy** the processed result for use in your code.',
  },
  { id: 'sql-to-linq', name: 'SQL to LINQ', description: 'Convert SQL SELECT queries to LINQ method syntax — WHERE, ORDER BY, GROUP BY, HAVING, DISTINCT, TOP online', category: 'dotnet', icon: '🔃', tags: ['sql', 'linq', 'csharp', 'c#', 'dotnet', 'query', 'convert', 'ef', 'entity framework', 'online'], popular: true, new: true, seoTitle: 'SQL to LINQ Converter — C# Query Syntax | DevTools Online',
    seoDescription: 'Convert SQL SELECT queries to LINQ method syntax online. Free tool supporting WHERE, JOIN, GROUP BY, HAVING, and TOP operations for C# developers.',
    howToUse: '1. **Paste** your SQL SELECT query into the input.\n2. **Generate** the equivalent LINQ method syntax instantly.\n3. **Review** mapping of SQL clauses to LINQ methods.\n4. **Copy** the C# code into your Data Access Layer.',
    commonErrors: '- **Unsupported Syntax**: Complex subqueries or vendor-specific SQL functions may not have direct LINQ equivalents.',
  },

  // Diagram & Visualization
  { id: 'diagram-creator', name: 'Diagram Creator', description: 'Create flowcharts, sequence diagrams, ER diagrams, class diagrams, Gantt, mindmaps using Mermaid syntax — export SVG/PNG online', category: 'misc', icon: '🗂️', tags: ['diagram', 'mermaid', 'flowchart', 'sequence', 'erd', 'uml', 'class', 'gantt', 'mindmap', 'chart', 'online'], popular: true, new: true, seoTitle: 'Online Diagram Creator — Flowcharts, ERD, Sequence | DevTools Online', seoDescription: 'Create flowcharts, sequence diagrams, ER diagrams, class diagrams, Gantt charts and mindmaps with Mermaid — export SVG/PNG. Free, no signup.' },
  { id: 'erd-diagram', name: 'ERD Diagram', description: 'Paste CREATE TABLE SQL to generate an interactive Entity Relationship Diagram — drag tables, visualize FK relationships online', category: 'dotnet', icon: '🔗', tags: ['erd', 'sql', 'diagram', 'entity', 'relationship', 'table', 'schema', 'foreign key', 'database', 'online'], popular: true, new: true, seoTitle: 'ERD Diagram Generator from SQL | DevTools Online',
    seoDescription: 'Generate interactive Entity Relationship Diagrams (ERD) from SQL CREATE TABLE statements online. Free visualizer to map relationships and foreign keys instantly.',
    howToUse: '1. **Paste** one or more SQL CREATE TABLE statements into the editor.\n2. **Visualize** the tables and their relationships automatically.\n3. **Drag and drop** tables to organize your schema view.\n4. **Explore** foreign key links between entities.',
  },
  { id: 'sql-plan-viewer', name: 'SQL Execution Plan Viewer', description: 'Visualize PostgreSQL EXPLAIN ANALYZE and MySQL EXPLAIN output as an annotated tree — spot slow operations instantly online', category: 'dotnet', icon: '📊', tags: ['sql', 'explain', 'execution', 'plan', 'postgresql', 'mysql', 'performance', 'query', 'index', 'online'], popular: true, new: true, seoTitle: 'SQL Execution Plan Viewer — EXPLAIN ANALYZE | DevTools Online',
    seoDescription: 'Visualize PostgreSQL and MySQL execution plans online. Free tool to parse EXPLAIN output as an annotated tree to identify performance bottlenecks instantly.',
    howToUse: '1. **Run** `EXPLAIN (FORMAT JSON) ...` in Postgres or `EXPLAIN ...` in MySQL.\n2. **Paste** the execution plan output into the viewer.\n3. **Analyze** the tree to find high-cost nodes and sequential scans.\n4. **Optimize** your query based on the visual warnings.',
    commonErrors: '- **Format Mismatch**: Ensure you use the correct format (JSON for Postgres) for optimal visualization.',
  },
  { id: 'log-viewer', name: 'Log Viewer', description: 'Parse and view structured logs — JSON Lines (Serilog, Pino), .NET NLog, Apache/Nginx access logs — filter by level, search online', category: 'misc', icon: '📋', tags: ['log', 'viewer', 'serilog', 'nlog', 'json', 'apache', 'nginx', 'dotnet', 'debug', 'error', 'filter', 'online'], popular: true, new: true, seoTitle: 'Log Viewer — JSON Logs, Serilog, NLog, Apache | DevTools Online', seoDescription: 'Parse structured logs online — JSON Lines (Serilog, Pino), .NET NLog, Apache/Nginx access logs. Filter by level, search, highlight — free, no signup.' },

  // Network / Web tools
  { id: 'dns-lookup', name: 'DNS Lookup', description: 'Query DNS records for any domain — A, AAAA, MX, TXT, NS, CNAME, SOA and more via Cloudflare DNS-over-HTTPS online', category: 'web', icon: '🌐', tags: ['dns', 'lookup', 'domain', 'a', 'mx', 'txt', 'ns', 'cname', 'nameserver', 'record', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Queries sent via Cloudflare DNS-over-HTTPS (1.1.1.1). Domain names you look up leave your browser.', seoTitle: 'DNS Lookup Tool — A, MX, TXT, NS Records | DevTools Online', seoDescription: 'Query DNS records for any domain online — A, AAAA, MX, TXT, NS, CNAME, SOA via Cloudflare DoH. Fast, accurate, free — no account needed.' },
  { id: 'ip-lookup', name: 'IP Address Lookup', description: 'Look up geolocation, ASN, timezone and organization for any IP address — detects your own IP automatically online', category: 'web', icon: '📍', tags: ['ip', 'lookup', 'geolocation', 'asn', 'country', 'city', 'timezone', 'network', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'IP data fetched from ipapi.co. The IP address you query is sent to their API.', seoTitle: 'IP Address Lookup — Geolocation & ASN | DevTools Online', seoDescription: 'Look up IP geolocation, ASN, timezone and ISP for any IP address online. Auto-detects your own IP — free, instant, powered by ipapi.co.' },
  { id: 'ssl-checker', name: 'SSL Certificate Checker', description: 'Check SSL/TLS certificate validity, expiry date, issuer and SANs for any domain via Certificate Transparency logs online', category: 'web', icon: '🔒', tags: ['ssl', 'tls', 'certificate', 'https', 'expiry', 'domain', 'security', 'crt.sh', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Certificate data fetched from crt.sh (Certificate Transparency logs). The domain you query is sent to their API.', seoTitle: 'SSL Certificate Checker — Expiry & Validity | DevTools Online', seoDescription: 'Check SSL/TLS certificate validity, expiry date, issuer and SANs for any domain online. Spot expiring certificates before they cause downtime.' },
  { id: 'http-request-builder', name: 'HTTP Request Builder', description: 'Build and send HTTP requests with custom headers, body, params — generate fetch, axios, curl, Python code snippets online', category: 'web', icon: '📡', tags: ['http', 'request', 'api', 'rest', 'fetch', 'axios', 'curl', 'get', 'post', 'headers', 'builder', 'online'], popular: true, new: true, privacy: 'network', networkNote: 'Requests are sent directly from your browser to the target URL you specify.', seoTitle: 'HTTP Request Builder & API Tester | DevTools Online', seoDescription: 'Build and send HTTP requests with custom headers, body & params. Generate fetch, axios, curl, Python snippets — free online API testing tool.' },
  { id: 'user-agent-parser', name: 'User-Agent Parser', description: 'Parse User-Agent strings to detect browser, OS, device type and brand — analyze any UA or test your own browser online', category: 'web', icon: '🕵️', tags: ['user-agent', 'browser', 'os', 'device', 'parse', 'chrome', 'firefox', 'safari', 'mobile', 'detect', 'online'], new: true, seoTitle: 'User-Agent Parser — Browser & OS Detection | DevTools Online', seoDescription: 'Parse User-Agent strings to detect browser, OS, device type and brand online. Auto-analyzes your own UA — free, instant, no signup required.' },
  { id: 'og-preview', name: 'OpenGraph Previewer', description: 'Preview and generate Open Graph meta tags with live mockups for Facebook, Twitter, LinkedIn and Google online', category: 'web', icon: '🖼️', tags: ['opengraph', 'og', 'preview', 'meta', 'tags', 'facebook', 'twitter', 'linkedin', 'seo', 'generator', 'online'], new: true, seoTitle: 'OpenGraph Previewer & Meta Tag Generator | DevTools Online', seoDescription: 'Preview and generate Open Graph meta tags online. Live interactive mockups for Facebook, Twitter (X), LinkedIn and Google Search. Free, no signup, instant results.' },

  // Color tools
  { id: 'color-extractor', name: 'Color Extractor', description: 'Upload an image to extract its dominant color palette — copy HEX, RGB, HSL values with proportional preview strip online', category: 'color', icon: '🎨', tags: ['color', 'palette', 'extract', 'image', 'dominant', 'hex', 'rgb', 'hsl', 'online'], new: true, seoTitle: 'Color Extractor from Image | DevTools Online', seoDescription: 'Upload an image to extract its dominant color palette online — copy HEX, RGB, HSL values with proportional preview. Free, no signup, client-side.' },
  { id: 'color-contrast', name: 'Color Contrast Checker', description: 'Check WCAG 2.1 color contrast ratio — AA and AAA compliance for normal/large text with live preview online', category: 'color', icon: '👁️', tags: ['color', 'contrast', 'wcag', 'accessibility', 'a11y', 'aa', 'aaa', 'ratio', 'online'], new: true, seoTitle: 'Color Contrast Checker — WCAG AA & AAA | DevTools Online', seoDescription: 'Check WCAG 2.1 color contrast ratio online — AA and AAA compliance for normal and large text with live preview. Free, instant, no signup needed.' },

  // CSS / Web visual
  { id: 'css-filter-generator', name: 'CSS Filter Generator', description: 'Visually adjust blur, brightness, contrast, hue-rotate and more — generates CSS filter property with live preview online', category: 'web', icon: '🎛️', tags: ['css', 'filter', 'blur', 'brightness', 'contrast', 'grayscale', 'sepia', 'generator', 'online'], new: true, seoTitle: 'CSS Filter Generator — Blur, Brightness, Contrast | DevTools Online', seoDescription: 'Visually adjust CSS filter values — blur, brightness, contrast, hue-rotate, grayscale, sepia — with live preview. Free, no signup, copy-ready CSS.' },
  { id: 'px-to-rem', name: 'Px ↔ Rem Converter', description: 'Convert between px and rem units with configurable base font size — includes reference table and CSS snippet online', category: 'web', icon: '📐', tags: ['px', 'rem', 'converter', 'css', 'font-size', 'responsive', 'units', 'online'], new: true, seoTitle: 'Px to Rem Converter — CSS Units | DevTools Online', seoDescription: 'Convert between px and rem CSS units online with configurable base font size. Includes reference table and CSS snippet — free, instant, no signup.' },
  { id: 'svg-previewer', name: 'SVG Previewer', description: 'Preview and edit SVG code with zoom, background options, element info — export as SVG or PNG online', category: 'web', icon: '✏️', tags: ['svg', 'preview', 'editor', 'zoom', 'export', 'png', 'vector', 'online'], new: true, seoTitle: 'SVG Previewer & Editor | DevTools Online', seoDescription: 'Preview and edit SVG code with zoom, background color options and element info online. Export as SVG or PNG — free, no signup, runs in browser.' },

  // Crypto / Security
  { id: 'password-strength', name: 'Password Strength Checker', description: 'Check password strength with entropy score, crack time estimate, WCAG checklist and improvement suggestions online', category: 'crypto', icon: '🔑', tags: ['password', 'strength', 'entropy', 'security', 'crack', 'checker', 'validate', 'online'], new: true, seoTitle: 'Password Strength Checker | DevTools Online',
    seoDescription: 'Check password strength and entropy score online. Get crack time estimates and WCAG security checklist with zero data uploads for maximum privacy.',
    howToUse: '1. **Type** your password into the input field.\n2. **Analyze** entropy score and "Time to Crack" visual indicators.\n3. **Review** checklist (Missing symbols, repeated chars, etc.).\n4. **Iterate** your password until you reach "Very Strong" status.',
    commonErrors: '- **Dictionary Words**: Passwords with common words are vulnerable even if long.\n- **Low Entropy**: Simple patterns (like 123456) result in low security.',
  },
  { id: 'cert-decoder', name: 'Certificate Decoder', description: 'Decode X.509 PEM certificates — view subject, issuer, validity dates, serial, extensions and public key info online', category: 'crypto', icon: '📜', tags: ['certificate', 'x509', 'pem', 'ssl', 'tls', 'decode', 'x.509', 'openssl', 'security', 'online'], new: true, seoTitle: 'X.509 Certificate Decoder — PEM Parser | DevTools Online',
    seoDescription: 'Decode X.509 PEM certificates online to view subject, issuer, validity, and public key info. Free SSL/TLS certificate parser with 100% local processing.',
    howToUse: '1. **Paste** PEM certificate (starting with `-----BEGIN CERTIFICATE-----`).\n2. **Analyze** Subject, Issuer, Serial Number, and Extensions.\n3. **Check** validity dates to ensure it is not expired.\n4. **Inspect** public key details and fingerprints.',
    commonErrors: '- **Incomplete PEM**: Ensure you include BEGIN and END header/footer lines.\n- **Wrong Format**: This tool specifically decodes X.509 PEM certificates.',
  },

  // Generator
  { id: 'national-id-generator', name: 'National ID Generator', description: 'Generate test national identity numbers — Vietnam CCCD, US SSN, UK NI Number, Singapore NRIC, Germany, France online', category: 'generator', icon: '🪪', tags: ['national', 'id', 'identity', 'ssn', 'cccd', 'nric', 'generator', 'test', 'fake', 'online'], new: true, seoTitle: 'National ID Generator — Test Data | DevTools Online', seoDescription: 'Generate test national identity numbers online — Vietnam CCCD, US SSN, UK NI, Singapore NRIC, Germany, France. Free, no signup, for testing only.' },

  // Formatter
  { id: 'xml-minifier', name: 'XML Minifier / Formatter', description: 'Minify XML by removing whitespace and comments, or format/beautify XML with configurable indentation online', category: 'formatter', icon: '📄', tags: ['xml', 'minify', 'format', 'beautify', 'compress', 'whitespace', 'comments', 'online'], new: true, seoTitle: 'XML Minifier & Formatter | DevTools Online', seoDescription: 'Minify XML by removing whitespace and comments online, or format and beautify with configurable indentation. Free, instant, no signup, runs in browser.' },

  // SQL Reference
  { id: 'sql-syntax', name: 'SQL Syntax Reference', description: 'Complete SQL syntax reference with copy-ready examples — DDL, SELECT, JOINs, CTEs, Window Functions, DML, Transactions online', category: 'dotnet', icon: '📖', tags: ['sql', 'syntax', 'reference', 'select', 'join', 'ddl', 'dml', 'cte', 'window', 'functions', 'tsql', 'online'], popular: true, new: true, seoTitle: 'SQL Syntax Reference & Cheat Sheet | DevTools Online',
    seoDescription: 'Complete SQL syntax reference and cheat sheet with copy-ready examples. Browse T-SQL, PostgreSQL, and MySQL syntax for JOINs, CTEs, and Window Functions.',
    howToUse: '1. **Search** for a specific SQL clause or function in the reference.\n2. **Read** clear explanations and usage rules.\n3. **View** practical code examples for different database engines.\n4. **Copy** snippets to use in your queries.',
  },

  // AI Tools
  { id: 'ai-token-counter', name: 'Token Counter', description: 'Estimate token count for GPT, Claude and Gemini models — track context usage and cost before calling the API online', category: 'ai', icon: '🪙', tags: ['ai', 'token', 'gpt', 'claude', 'gemini', 'openai', 'anthropic', 'count', 'context', 'online'], new: true, popular: true, seoTitle: 'AI Token Counter — GPT, Claude, Gemini | DevTools Online',
    seoDescription: 'Estimate token count for GPT, Claude, and Gemini models online. Free tool to track context window usage and API costs before sending prompts.',
    howToUse: '1. **Paste** your prompt text into the counter.\n2. **Select** the target model (e.g., GPT-4o, Claude 3.5).\n3. **Observe** token count and estimated cost update in real-time.\n4. **Optimize** your prompt to stay within context limits.',
  },
  { id: 'ai-cost-calculator', name: 'AI Cost Calculator', description: 'Calculate API cost for any AI model — enter input/output tokens and get exact pricing for GPT-4o, Claude, Gemini and more online', category: 'ai', icon: '💰', tags: ['ai', 'cost', 'price', 'gpt', 'claude', 'gemini', 'openai', 'anthropic', 'token', 'calculator', 'online'], new: true, privacy: 'network', networkNote: 'Pricing data fetched from LiteLLM. No prompt content or token data leaves your browser.', seoTitle: 'AI API Cost Calculator — GPT, Claude, Gemini | DevTools Online',
    seoDescription: 'Calculate AI API costs for GPT-4, Claude, Gemini, and more online. Enter input/output tokens to get exact pricing based on current LiteLLM data.',
    howToUse: '1. **Choose** your AI provider and model version.\n2. **Input** the number of tokens or words for input and output.\n3. **Calculate** the total USD cost instantly.\n4. **Compare** pricing across different models to optimize your budget.',
  },
  { id: 'ai-prompt-builder', name: 'Prompt Builder', description: 'Build structured AI prompts with System / User / Assistant roles — export as OpenAI JSON or plain text online', category: 'ai', icon: '🧱', tags: ['ai', 'prompt', 'system', 'user', 'assistant', 'openai', 'chatgpt', 'builder', 'json', 'online'], new: true, seoTitle: 'AI Prompt Builder — System, User, Assistant Roles | DevTools Online',
    seoDescription: 'Build structured AI prompts with System, User, and Assistant roles online. Free tool to generate OpenAI-compatible JSON or plain text prompts instantly.',
    howToUse: '1. **Add** message blocks for System, User, or Assistant roles.\n2. **Write** clear instructions and context in each block.\n3. **Preview** the formatted prompt as a JSON array or text.\n4. **Copy** the result for your API calls or LLM interactions.',
  },
  { id: 'ai-model-comparison', name: 'Model Comparison', description: 'Compare GPT, Claude, Gemini and open-source models — context window, pricing, strengths side by side online', category: 'ai', icon: '⚖️', tags: ['ai', 'model', 'compare', 'gpt', 'claude', 'gemini', 'llama', 'context', 'price', 'online'], new: true, privacy: 'network', networkNote: 'Model pricing data fetched from LiteLLM. No personal data is sent.', seoTitle: 'AI Model Comparison — GPT vs Claude vs Gemini | DevTools Online',
    seoDescription: 'Compare GPT, Claude, Gemini, and Llama models online side-by-side. Free reference for context windows, pricing, and specific model strengths.',
    howToUse: '1. **Filter** models by provider or capability.\n2. **Compare** key metrics like maximum tokens and per-million pricing.\n3. **Read** summaries of strengths and ideal use cases.\n4. **Select** the best model for your specific technical requirements.',
  },
  { id: 'ai-json-to-prompt', name: 'JSON → Prompt', description: 'Convert JSON data into a natural language prompt — describe objects, arrays and values in readable sentences online', category: 'ai', icon: '🔀', tags: ['ai', 'json', 'prompt', 'convert', 'natural', 'language', 'describe', 'online'], new: true, seoTitle: 'JSON to Natural Language Prompt Converter | DevTools Online',
    seoDescription: 'Convert JSON data into natural language prompts online. Free tool to describe complex JSON objects and arrays in readable sentences for LLMs.',
    howToUse: '1. **Paste** your JSON payload into the source editor.\n2. **Generate** a natural language description automatically.\n3. **Review** prompt to ensure it captures all data relationships.\n4. **Copy** the text to use in your AI model instructions.',
  },
  { id: 'ai-system-prompt', name: 'System Prompt Generator', description: 'Generate system prompts for AI assistants — choose use case, tone and constraints to get a ready-to-use prompt online', category: 'ai', icon: '⚙️', tags: ['ai', 'system', 'prompt', 'generator', 'assistant', 'chatbot', 'instruction', 'online'], new: true, seoTitle: 'AI System Prompt Generator | DevTools Online',
    seoDescription: 'Generate optimized AI system prompts online. Choose use cases, tones, and constraints to build high-quality instructions for AI assistants instantly.',
    howToUse: '1. **Select** a primary use case (e.g., Coding Assistant).\n2. **Choose** desired tone and set behavioral constraints.\n3. **Generate** a comprehensive system prompt.\n4. **Refine** and copy prompt for your model configuration.',
  },
]
