import { useState, useEffect } from 'react'
import FileDropTextarea from '../components/FileDropTextarea'
import { usePersistentState } from '../hooks/usePersistentState'
import { useShareableState } from '../hooks/useShareableState'
import { Zap, Trash2, Check, AlertTriangle, Minus, Plus, ArrowLeftRight, Info, Download } from 'lucide-react'
import { formatJson } from '../core/json'

function diffObjects(a: any, b: any, path = ''): string[] {
  const results: string[] = []
  if (JSON.stringify(a) === JSON.stringify(b)) return results

  if (typeof a !== typeof b || a === null || b === null) {
    results.push(`~ ${path || 'root'}: ${JSON.stringify(a)} → ${JSON.stringify(b)}`)
    return results
  }

  if (Array.isArray(a) && Array.isArray(b)) {
    const len = Math.max(a.length, b.length)
    for (let i = 0; i < len; i++) {
      if (i >= a.length) results.push(`+ ${path}[${i}]: ${JSON.stringify(b[i])}`)
      else if (i >= b.length) results.push(`- ${path}[${i}]: ${JSON.stringify(a[i])}`)
      else results.push(...diffObjects(a[i], b[i], `${path}[${i}]`))
    }
    return results
  }

  if (typeof a === 'object' && typeof b === 'object') {
    const aObj = a
    const bObj = b
    const keys = new Set([...Object.keys(aObj), ...Object.keys(bObj)])
    for (const key of keys) {
      const p = path ? `${path}.${key}` : key
      if (!(key in aObj)) results.push(`+ ${p}: ${JSON.stringify(bObj[key])}`)
      else if (!(key in bObj)) results.push(`- ${p}: ${JSON.stringify(aObj[key])}`)
      else results.push(...diffObjects(aObj[key], bObj[key], p))
    }
    return results
  }

  results.push(`~ ${path}: ${JSON.stringify(a)} → ${JSON.stringify(b)}`)
  return results
}

const SAMPLE_A = '{"id":1,"name":"Alice","role":"Engineer","salary":95000,"active":true}'
const SAMPLE_B = '{"id":1,"name":"Alice","role":"Senior Engineer","salary":110000,"active":true,"tags":["lead"]}'

export default function JsonDiff() {
  const [left, setLeft] = usePersistentState('tool-json-diff-left', SAMPLE_A)
  const [right, setRight] = usePersistentState('tool-json-diff-right', SAMPLE_B)
  
  // Accept incoming state into the 'Left' (Original) field
  useShareableState(left, setLeft)
  
  const [diffs, setDiffs] = useState<string[]>([])
  const [error, setError] = useState('')
  const [compared, setCompared] = useState(false)

  const compare = () => {
    if (!left.trim() || !right.trim()) {
      setDiffs([])
      setCompared(false)
      return
    }
    try {
      // Auto-format both sides if valid JSON
      const { output: leftFmt } = formatJson(left)
      const { output: rightFmt } = formatJson(right)
      if (leftFmt && leftFmt !== left) setLeft(leftFmt)
      if (rightFmt && rightFmt !== right) setRight(rightFmt)

      const a = JSON.parse(leftFmt || left)
      const b = JSON.parse(rightFmt || right)
      setDiffs(diffObjects(a, b))
      setError('')
      setCompared(true)
    } catch (e) {
      setError((e as Error).message)
      setCompared(false)
    }
  }

  const swap = () => {
    const temp = left
    setLeft(right)
    setRight(temp)
  }

  const downloadReport = () => {
    if (diffs.length === 0) return
    const plus = diffs.filter(d => d.startsWith('+')).length
    const minus = diffs.filter(d => d.startsWith('-')).length
    const changed = diffs.filter(d => d.startsWith('~')).length
    
    const report = [
      `JSON Diff Report - ${new Date().toLocaleString()}`,
      `---------------------------------------`,
      `Summary:`,
      `- Added: ${plus}`,
      `- Removed: ${minus}`,
      `- Changed: ${changed}`,
      `- Total: ${diffs.length}`,
      `---------------------------------------`,
      `Differences:`,
      ...diffs.map(d => `${d.startsWith('+') ? '[+]' : d.startsWith('-') ? '[-]' : '[*]'} ${d.slice(1).trim()}`),
      `---------------------------------------`,
      `Generated by DevTools Online`
    ].join('\n')

    const blob = new Blob([report], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'json-diff-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  // Auto-compare on change if both exist
  useEffect(() => {
    if (left.trim() && right.trim()) {
      const t = setTimeout(compare, 300)
      return () => clearTimeout(t)
    }
  }, [left, right])

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <h2 className="text-sm font-bold text-gray-400 uppercase tracking-widest">Compare JSON Objects</h2>
        <div className="flex items-center gap-2">
           <button onClick={swap} className="btn-ghost text-xs font-medium gap-1.5 flex items-center">
                <ArrowLeftRight size={12} /> Swap
           </button>
           <button onClick={() => { setLeft(SAMPLE_A); setRight(SAMPLE_B) }} className="btn-ghost text-xs font-medium">Reset Samples</button>
           <button onClick={() => { setLeft(''); setRight(''); setDiffs([]) }} className="btn-ghost text-xs font-medium text-red-500">
                <Trash2 size={12} /> Clear Both
           </button>
           <button onClick={compare} className="btn-primary py-1.5 px-4 flex items-center gap-2">
                <Zap size={14} /> Compare Now
           </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div>
          <div className="tool-output-header">
            <label className="tool-label flex items-center gap-2">
              <span className="w-5 h-5 flex items-center justify-center bg-gray-100 dark:bg-gray-800 rounded">A</span>
              Original JSON
            </label>
          </div>
          <FileDropTextarea 
            className="h-64" 
            placeholder='Original JSON here...' 
            value={left} 
            onChange={setLeft} 
            accept=".json,text/plain,text/*" 
          />
        </div>
        <div>
          <div className="tool-output-header">
             <label className="tool-label flex items-center gap-2">
                <span className="w-5 h-5 flex items-center justify-center bg-gray-100 dark:bg-gray-800 rounded">B</span>
                Modified JSON
             </label>
          </div>
          <FileDropTextarea 
            className="h-64" 
            placeholder='Modified JSON here...' 
            value={right} 
            onChange={setRight} 
            accept=".json,text/plain,text/*" 
          />
        </div>
      </div>

      {error && (
        <div className="tool-msg tool-msg--error flex items-center gap-2">
          <AlertTriangle size={14} />
          {error}
        </div>
      )}

      {compared && (
        <div className="space-y-3 mt-6 animate-in slide-in-from-top-2 duration-300">
           <div className="flex items-center gap-4 flex-wrap">
              <h3 className="font-bold text-gray-900 dark:text-white">Differences Found</h3>
              <div className="flex items-center gap-2">
                 <span className="flex items-center gap-1.5 text-[10px] font-bold px-2 py-0.5 rounded-full bg-green-100 text-green-700 dark:bg-green-900/30">
                    <Plus size={10} /> {diffs.filter(d => d.startsWith('+')).length} Added
                 </span>
                 <span className="flex items-center gap-1.5 text-[10px] font-bold px-2 py-0.5 rounded-full bg-red-100 text-red-700 dark:bg-red-900/30">
                    <Minus size={10} /> {diffs.filter(d => d.startsWith('-')).length} Removed
                 </span>
                 <span className="flex items-center gap-1.5 text-[10px] font-bold px-2 py-0.5 rounded-full bg-amber-100 text-amber-700 dark:bg-amber-900/30">
                    <Info size={10} /> {diffs.filter(d => d.startsWith('~')).length} Changed
                 </span>
              </div>
              <button 
                onClick={downloadReport} 
                className="ml-auto btn-ghost text-xs flex items-center gap-1.5 text-primary-600 hover:text-primary-700"
              >
                <Download size={14} /> Download Report
              </button>
           </div>

           <div className="bg-gray-950 rounded-2xl p-6 border border-gray-800 overflow-hidden font-mono text-xs sm:text-sm shadow-xl">
            {diffs.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-6 text-green-400 gap-2">
                 <Check size={32} />
                 <p className="font-bold">JSON objects are identical!</p>
              </div>
            ) : (
              <div className="space-y-1 overflow-x-auto custom-scrollbar max-h-80">
                {diffs.map((line, i) => {
                  const isPlus = line.startsWith('+')
                  const isMinus = line.startsWith('-')
                  const isChange = line.startsWith('~')
                  return (
                    <div key={i} className={`flex items-start gap-3 px-2 py-1 rounded transition-colors group cursor-default whitespace-pre
                      ${isPlus ? 'bg-green-500/10 text-green-400' : 
                        isMinus ? 'bg-red-500/10 text-red-400' : 
                        'bg-amber-500/10 text-amber-400'}`}>
                      <span className="w-4 shrink-0 font-bold opacity-60">
                         {isPlus ? '+' : isMinus ? '-' : '~'}
                      </span>
                      <span className="break-all">{line.slice(1).trim()}</span>
                    </div>
                  )
                })}
              </div>
            )}
           </div>
        </div>
      )}
    </div>
  )
}
